'use strict';

angular.module('aeSupportMod', [])
.value('toxicityGrades', {
  'Anemia': ['1','2','3','4','5'],
  'Bone marrow hypocellular': ['3','4','5'],
  'Disseminated intravascular coagulation': ['3','4','5'],
  'Febrile neutropenia': ['3','4','5'],
  'Hemolysis': ['3','4','5'],
  'Hemolytic uremic syndrome': ['3','4','5'],
  'Leukocytosis': ['3','4','5'],
  'Lymph node pain': ['3'],
  'Spleen disorder': ['4','5'],
  'Thrombotic thrombocytopenic purpura': ['3','4','5'],
  'Blood and lymphatic system disorder - Other, specify': ['3','4','5'],

  'Acute coronary syndrome': ['3','4','5'],
  'Aortic valve disease': ['3','4','5'],
  'Asystole': ['4','5'],
  'Atrial fibrillation': ['3','4','5'],
  'Atrial flutter': ['3','4','5'],
  'Atrioventricular block complete': ['3','4','5'],
  'Cardiac arrest': ['4','5'],
  'Chest pain - cardiac': ['3'],
  'Conduction disorder': ['3','4','5'],
  'Constrictive pericarditis': ['3','4','5'],
  'Heart failure': ['3','4','5'],
  'Left ventricular systolic dysfunction': ['3','4','5'],
  'Mitral valve disease': ['3','4','5'],
  'Mobitz (type) II atrioventricular block': ['3','4','5'],
  'Mobitz type I': ['3','4','5'],
  'Myocardial infarction': ['3','4','5'],
  'Myocarditis': ['3','4','5'],
  'Paroxysmal atrial tachycardia': ['3','4','5'],
  'Pericardial effusion': ['3','4','5'],
  'Pericardial tamponade': ['4','5'],
  'Pericarditis': ['3','4','5'],
  'Pulmonary valve disease': ['3','4','5'],
  'Restrictive cardiomyopathy': ['3','4','5'],
  'Right ventricular dysfunction': ['3','4','5'],
  'Sick sinus syndrome': ['3','4','5'],
  'Sinus bradycardia': ['3','4','5'],
  'Sinus tachycardia': ['3'],
  'Supraventricular tachycardia': ['3','4','5'],
  'Tricuspid valve disease': ['3','4','5'],
  'Ventricular arrhythmia': ['3','4','5'],
  'Ventricular fibrillation': ['4','5'],
  'Ventricular tachycardia': ['3','4','5'],
  'Wolff-Parkinson-White syndrome': ['3','4','5'],
  'Cardiac disorder - Other, specify': ['3','4','5'],
  'Congenital, familial and genetic disorders - Other, specify': ['3','4','5'],
  'Ear pain': ['3'],
  'External ear inflammation': ['3','4','5'],
  'External ear pain': ['3'],
  'Hearing impaired': ['3','4'],
  'Middle ear inflammation': ['3','4','5'],
  'Tinnitus': ['3'],
  'Vertigo': ['3'],
  'Vestibular disorder': ['3'],
  'Ear and labyrinth disorders - Other, specify': ['3','4','5'],

  'Adrenal insufficiency': ['3','4','5'],
  'Cushingoid': ['3','4','5'],
  'Delayed puberty': ['3'],
  'Hyperthyroidism': ['3','4','5'],
  'Hypoparathyroidism': ['3','4','5'],
  'Hypothyroidism': ['3','4','5'],
  'Endocrine disorders - Other, specify': ['3','4','5'],

  'Blurred vision': ['3'],
  'Cataract': ['3','4'],
  'Conjunctivitis': ['3'],
  'Corneal ulcer': ['3','4'],
  'Dry eye': ['3'],
  'Extraocular muscle paresis': ['3'],
  'Eye pain': ['3'],
  'Eyelid function disorder': ['3'],
  'Flashing lights': ['3'],
  'Floaters': ['3'],
  'Glaucoma': ['4'],
  'Keratitis': ['3','4'],
  'Night blindness': ['3','4'],
  'Optic nerve disorder': ['3','4'],
  'Papilledema': ['3','4'],
  'Photophobia': ['3'],
  'Retinal detachment': ['3','4'],
  'Retinal tear': ['3','4'],
  'Retinal vascular disorder': ['3'],
  'Retinopathy': ['3','4'],
  'Scleral disorder': ['3','4'],
  'Uveitis': ['3','4'],
  'Vitreous hemorrhage': ['3','4'],
  'Watering eyes': ['3'],
  'Eye disorders - Other, specify': ['3','4','5'],

  'Abdominal distension': ['3'],
  'Abdominal pain': ['3'],
  'Anal fistula': ['3','4','5'],
  'Anal hemorrhage': ['3','4','5'],
  'Anal mucositis': ['3','4','5'],
  'Anal necrosis': ['3','4','5'],
  'Anal pain': ['3'],
  'Anal stenosis': ['3','4','5'],
  'Anal ulcer': ['3','4','5'],
  'Ascites': ['3','4','5'],
  'Cecal hemorrhage': ['3','4','5'],
  'Cheilitis': ['3'],
  'Colitis': ['3','4','5'],
  'Colonic fistula': ['3','4','5'],
  'Colonic hemorrhage': ['3','4','5'],
  'Colonic obstruction': ['3','4','5'],
  'Colonic perforation': ['3','4','5'],
  'Colonic stenosis': ['3','4','5'],
  'Colonic ulcer': ['3','4','5'],
  'Constipation': ['3','4','5'],
  'Dental caries': ['3'],
  'Diarrhea': ['3','4','5'],
  'Dry mouth': ['3'],
  'Duodenal fistula': ['3','4','5'],
  'Duodenal hemorrhage': ['3','4','5'],
  'Duodenal obstruction': ['3','4','5'],
  'Duodenal perforation': ['3','4','5'],
  'Duodenal stenosis': ['3','4','5'],
  'Duodenal ulcer': ['3','4','5'],
  'Dyspepsia': ['3'],
  'Dysphagia': ['3','4','5'],
  'Enterocolitis': ['3','4','5'],
  'Enterovesical fistula': ['3','4','5'],
  'Esophageal fistula': ['3','4','5'],
  'Esophageal hemorrhage': ['3','4','5'],
  'Esophageal necrosis': ['3','4','5'],
  'Esophageal obstruction': ['3','4','5'],
  'Esophageal pain': ['3'],
  'Esophageal perforation': ['3','4','5'],
  'Esophageal stenosis': ['3','4','5'],
  'Esophageal ulcer': ['3','4','5'],
  'Esophageal varices hemorrhage': ['3','4','5'],
  'Esophagitis': ['3','4','5'],
  'Fecal incontinence': ['3'],
  'Gastric fistula': ['3','4','5'],
  'Gastric hemorrhage': ['3','4','5'],
  'Gastric necrosis': ['3','4','5'],
  'Gastric perforation': ['3','4','5'],
  'Gastric stenosis': ['3','4','5'],
  'Gastric ulcer': ['3','4','5'],
  'Gastritis': ['3','4','5'],
  'Gastroesophageal reflux disease': ['3'],
  'Gastrointestinal fistula': ['3','4','5'],
  'Gastrointestinal pain': ['3'],
  'Gastroparesis': ['3'],
  'Gingival pain': ['3'],
  'Hemorrhoidal hemorrhage': ['3','4','5'],
  'Hemorrhoids': ['3'],
  'Ileal fistula': ['3','4','5'],
  'Ileal hemorrhage': ['3','4','5'],
  'Ileal obstruction': ['3','4','5'],
  'Ileal perforation': ['3','4','5'],
  'Ileal stenosis': ['3','4','5'],
  'Ileal ulcer': ['3','4','5'],
  'Ileus': ['3','4','5'],
  'Intra-abdominal hemorrhage': ['3','4','5'],
  'Jejunal fistula': ['3','4','5'],
  'Jejunal hemorrhage': ['3','4','5'],
  'Jejunal obstruction': ['3','4','5'],
  'Jejunal perforation': ['3','4','5'],
  'Jejunal stenosis': ['3','4','5'],
  'Jejunal ulcer': ['3','4','5'],
  'Lip pain': ['3'],
  'Lower gastrointestinal hemorrhage': ['3','4','5'],
  'Malabsorption': ['3','4','5'],
  'Mucositis oral': ['3','4','5'],
  'Nausea': ['3'],
  'Obstruction gastric': ['3','4','5'],
  'Oral cavity fistula': ['3','4','5'],
  'Oral dysesthesia': ['3'],
  'Oral hemorrhage': ['3','4','5'],
  'Oral pain': ['3'],
  'Pancreatic duct stenosis': ['3','4','5'],
  'Pancreatic fistula': ['3','4','5'],
  'Pancreatic hemorrhage': ['3','4','5'],
  'Pancreatic necrosis': ['4','5'],
  'Pancreatitis': ['3','4','5'],
  'Periodontal disease': ['3'],
  'Peritoneal necrosis': ['4','5'],
  'Proctitis': ['3','4','5'],
  'Rectal fistula': ['3','4','5'],
  'Rectal hemorrhage': ['3','4','5'],
  'Rectal mucositis': ['3','4','5'],
  'Rectal necrosis': ['3','4','5'],
  'Rectal obstruction': ['3','4','5'],
  'Rectal pain': ['3'],
  'Rectal perforation': ['3','4','5'],
  'Rectal stenosis': ['3','4','5'],
  'Rectal ulcer': ['3','4','5'],
  'Retroperitoneal hemorrhage': ['3','4','5'],
  'Salivary duct inflammation': ['3','4','5'],
  'Salivary gland fistula': ['3','4','5'],
  'Small intestinal mucositis': ['3','4','5'],
  'Small intestinal obstruction': ['3','4','5'],
  'Small intestinal perforation': ['3','4','5'],
  'Small intestinal stenosis': ['3','4','5'],
  'Small intestine ulcer': ['3','4','5'],
  'Stomach pain': ['3'],
  'Tooth development disorder': ['3'],
  'Toothache': ['3'],
  'Typhlitis': ['3','4','5'],
  'Upper gastrointestinal hemorrhage': ['3','4','5'],
  'Vomiting': ['3','4','5'],
  'Gastrointestinal disorders - Other, specify': ['3','4','5'],

  'Chills': ['3'],
  'Death neonatal': ['5'],
  'Death NOS': ['5'],
  'Edema face': ['3'],
  'Edema limbs': ['3'],
  'Edema trunk': ['3'],
  'Facial pain': ['3'],
  'Fatigue': ['3'],
  'Fever': ['3','4','5'],
  'Flu like symptoms': ['3'],
  'Gait disturbance': ['3'],
  'Hypothermia': ['3','4','5'],
  'Infusion related reaction': ['3',' 4','5'],
  'Infusion site extravasation': ['3','4','5'],
  'Injection site reaction': ['3',' 4','5'],
  'Irritability': ['3'],
  'Localized edema': ['3'],
  'Multi-organ failure': ['3','4','5'],
  'Neck edema': ['3'],
  'Non-cardiac chest pain': ['3'],
  'Pain': ['3'],
  'Sudden death NOS': ['5'],
  'General disorders and administration site conditions - Other, specify': ['3','4','5'],

  'Bile duct stenosis': ['3','4','5'],
  'Biliary fistula': ['3','4','5'],
  'Cholecystitis': ['3','4','5'],
  'Gallbladder fistula': ['3','4','5'],
  'Gallbladder necrosis': ['4','5'],
  'Gallbladder obstruction': ['3','4','5'],
  'Gallbladder pain': ['3'],
  'Gallbladder perforation': ['4','5'],
  'Hepatic failure': ['4','5'],
  'Hepatic hemorrhage': ['3','4','5'],
  'Hepatic necrosis': ['4','5'],
  'Hepatic pain': ['3'],
  'Perforation bile duct': ['3','4','5'],
  'Portal hypertension': ['3','4','5'],
  'Portal vein thrombosis': ['3','4','5'],
  'Hepatobiliary disorders - Other, specify': ['3','4','5'],

  'Allergic reaction': ['3','4','5'],
  'Anaphylaxis': ['3','4','5'],
  'Autoimmune disorder': ['3','4','5'],
  'Cytokine release syndrome': ['3','4','5'],
  'Serum sickness': ['3','4','5'],
  'Immune system disorders - Other, specify': ['3','4','5'],

  'Abdominal infection': ['3','4','5'],
  'Anorectal infection': ['1','2','3','4','5'],
  'Appendicitis': ['3','4','5'],
  'Appendicitis perforated': ['2','3','4','5'],
  'Arteritis infective': ['3','4','5'],
  'Biliary tract infection': ['3','4','5'],
  'Bladder infection': ['2','3','4','5'],
  'Bone infection': ['3','4','5'],
  'Breast infection': ['2','3','4','5'],
  'Bronchial infection': ['2','3','4','5'],
  'Catheter related infection': ['2','3','4','5'],
  'Cecal infection': ['3','4','5'],
  'Cervicitis infection': ['2','3','4','5'],
  'Conjunctivitis infective': ['2','3','4','5'],
  'Corneal infection': ['2','3','4','5'],
  'Cranial nerve infection': ['3','4','5'],
  'Device related infection': ['3','4','5'],
  'Duodenal infection': ['2','3','4','5'],
  'Encephalitis infection': ['3','4','5'],
  'Encephalomyelitis infection': ['3','4','5'],
  'Endocarditis infective': ['3','4','5'],
  'Endophthalmitis': ['2','3','4'],
  'Enterocolitis infectious': ['2','3','4','5'],
  'Esophageal infection': ['2','3','4','5'],
  'Eye infection': ['2','3','4','5'],
  'Gallbladder infection': ['3','4','5'],
  'Gum infection': ['1','2','3','4','5'],
  'Hepatic infection': ['3','4','5'],
  'Hepatitis viral': ['1','3','4','5'],
  'Infective myositis': ['2','3','4','5'],
  'Joint infection': ['2','3','4','5'],
  'Kidney infection': ['3','4','5'],
  'Laryngitis': ['2','3','4','5'],
  'Lip infection': ['1','2','3'],
  'Lung infection': ['2','3','4','5'],
  'Lymph gland infection': ['2','3','4','5'],
  'Mediastinal infection': ['3','4','5'],
  'Meningitis': ['3','4','5'],
  'Mucosal infection': ['1','2','3','4','5'],
  'Nail infection': ['1','2','3'],
  'Otitis externa': ['2','3','4','5'],
  'Otitis media': ['2','3','4','5'],
  'Ovarian infection': ['2','3','4','5'],
  'Pancreas infection': ['3','4','5'],
  'Papulopustular rash': ['1','2','3','4','5'],
  'Paronychia': ['1','2','3'],
  'Pelvic infection': ['2','3','4','5'],
  'Penile infection': ['2','3','4','5'],
  'Periorbital infection': ['2','3','4','5'],
  'Peripheral nerve infection': ['2','3','4','5'],
  'Peritoneal infection': ['3','4','5'],
  'Pharyngitis': ['2','3','4','5'],
  'Phlebitis infective': ['2','3','4','5'],
  'Pleural infection': ['2','3','4','5'],
  'Prostate infection': ['2','3','4','5'],
  'Rash pustular': ['2','3'],
  'Rhinitis infective': ['2'],
  'Salivary gland infection': ['2','3','4','5'],
  'Scrotal infection': ['2','3','4','5'],
  'Sepsis': ['4','5'],
  'Sinusitis': ['2','3','4','5'],
  'Skin infection': ['1','2','3','4','5'],
  'Small intestine infection': ['2','3','4','5'],
  'Soft tissue infection': ['2','3','4','5'],
  'Splenic infection': ['3','4','5'],
  'Stoma site infection': ['1','2','3','4','5'],
  'Tooth infection': ['2','3','4','5'],
  'Tracheitis': ['2','3','4','5'],
  'Upper respiratory infection': ['2','3','4','5'],
  'Urethral infection': ['2','3','4','5'],
  'Urinary tract infection': ['2','3','4','5'],
  'Uterine infection': ['2','3','4','5'],
  'Vaginal infection': ['2','3','4','5'],
  'Vulval infection': ['1','2','3','4','5'],
  'Wound infection': ['2','3','4','5'],
  'Infections and infestations - Other, specify': ['1','2','3','4','5'],

  'Ankle fracture': ['3'],
  'Aortic injury': ['3','4','5'],
  'Arterial injury': ['3','4','5'],
  'Biliary anastomotic leak': ['3','4','5'],
  'Bladder anastomotic leak': ['3','4','5'],
  'Burn': ['3','4','5'],
  'Dermatitis radiation': ['3','4','5'],
  'Esophageal anastomotic leak': ['3','4','5'],
  'Fall': ['3'],
  'Fallopian tube anastomotic leak': ['3','4','5'],
  'Fallopian tube perforation': ['3','4','5'],
  'Fracture': ['3','4','5'],
  'Gastric anastomotic leak': ['3','4','5'],
  'Gastrointestinal anastomotic leak': ['3','4','5'],
  'Gastrointestinal stoma necrosis': ['3','4','5'],
  'Hip fracture': ['3','4'],
  'Injury to carotid artery': ['3','4','5'],
  'Injury to inferior vena cava': ['3','4'],
  'Injury to jugular vein': ['3','4','5'],
  'Injury to superior vena cava': ['3','4','5'],
  'Intestinal stoma leak': ['3','4','5'],
  'Intestinal stoma obstruction': ['3','4','5'],
  'Intestinal stoma site bleeding': ['3','4','5'],
  'Intraoperative arterial injury': ['3','4','5'],
  'Intraoperative breast injury': ['3','4','5'],
  'Intraoperative cardiac injury': ['3','4','5'],
  'Intraoperative ear injury': ['3','4','5'],
  'Intraoperative endocrine injury': ['3','4','5'],
  'Intraoperative gastrointestinal injury': ['3','4','5'],
  'Intraoperative head and neck injury': ['3','4','5'],
  'Intraoperative hemorrhage': ['3','4','5'],
  'Intraoperative hepatobiliary injury': ['3','4','5'],
  'Intraoperative musculoskeletal injury': ['3','4','5'],
  'Intraoperative neurological injury': ['3','4','5'],
  'Intraoperative ocular injury': ['3','4','5'],
  'Intraoperative renal injury': ['3','4','5'],
  'Intraoperative reproductive tract injury': ['3','4','5'],
  'Intraoperative respiratory injury': ['3','4','5'],
  'Intraoperative skin injury': ['3','4','5'],
  'Intraoperative splenic injury': ['3','4','5'],
  'Intraoperative urinary injury': ['3','4','5'],
  'Intraoperative venous injury': ['3','4','5'],
  'Kidney anastomotic leak': ['3','4','5'],
  'Large intestinal anastomotic leak': ['3','4','5'],
  'Pancreatic anastomotic leak': ['3','4','5'],
  'Pharyngeal anastomotic leak': ['3','4','5'],
  'Postoperative hemorrhage': ['3','4','5'],
  'Postoperative thoracic procedure complication': ['3','4','5'],
  'Prolapse of intestinal stoma': ['3','4','5'],
  'Prolapse of urostomy': ['3','4','5'],
  'Radiation recall reaction (dermatologic)': ['3','4','5'],
  'Rectal anastomotic leak': ['3','4','5'],
  'Seroma': ['3'],
  'Small intestinal anastomotic leak': ['3','4','5'],
  'Spermatic cord anastomotic leak': ['3','4','5'],
  'Spinal fracture': ['3','4','5'],
  'Stenosis of gastrointestinal stoma': ['3','4','5'],
  'Stomal ulcer': ['3'],
  'Tracheal hemorrhage': ['3','4','5'],
  'Tracheal obstruction': ['3','4','5'],
  'Tracheostomy site bleeding': ['3','4','5'],
  'Ureteric anastomotic leak': ['3','4','5'],
  'Urethral anastomotic leak': ['3','4','5'],
  'Urostomy leak': ['3','4','5'],
  'Urostomy obstruction': ['3','4','5'],
  'Urostomy site bleeding': ['3','4','5'],
  'Urostomy stenosis': ['3','4','5'],
  'Uterine anastomotic leak': ['3','4','5'],
  'Uterine perforation': ['3','4','5'],
  'Vaginal anastomotic leak': ['3','4','5'],
  'Vas deferens anastomotic leak': ['3','4','5'],
  'Vascular access complication': ['3','4','5'],
  'Venous injury': ['3','4','5'],
  'Wound complication': ['3','4','5'],
  'Wound dehiscence': ['3','4','5'],
  'Wrist fracture': ['3'],
  'Injury, poisoning and procedural complications - Other, specify': ['3','4','5'],

  'Activated partial thromboplastin time prolonged': ['3'],
  'Alanine aminotransferase increased': ['3','4'],
  'Alkaline phosphatase increased': ['3','4'],
  'Aspartate aminotransferase increased': ['3','4'],
  'Blood antidiuretic hormone abnormal': ['3'],
  'Blood bilirubin increased': ['3','4'],
  'Blood corticotrophin decreased': ['3'],
  'Blood gonadotrophin abnormal': ['3'],
  'Carbon monoxide diffusing capacity decreased': ['3'],
  'Cardiac troponin I increased': ['3'],
  'Cardiac troponin T increased': ['3'],
  'CD4 lymphocytes decreased': ['3','4'],
  'Cholesterol high': ['3','4'],
  'CPK increased': ['3','4'],
  'Creatinine increased': ['3','4'],
  'Ejection fraction decreased': ['3','4'],
  'Electrocardiogram QT corrected interval prolonged': ['3','4'],
  'Fibrinogen decreased': ['3','4'],
  'Forced expiratory volume decreased': ['3','4'],
  'GGT increased': ['3','4'],
  'Hemoglobin increased': ['3'],
  'INR increased': ['3'],
  'Lipase increased': ['3','4'],
  'Lymphocyte count decreased': ['3','4'],
  'Lymphocyte count increased': ['3'],
  'Neutrophil count decreased': ['1','2','3','4'],
  'Pancreatic enzymes decreased': ['3'],
  'Platelet count decreased': ['1','2','3','4'],
  'Serum amylase increased': ['3','4'],
  'Urine output decreased': ['3','4'],
  'Vital capacity abnormal': ['3'],
  'Weight gain': ['3'],
  'Weight loss': ['3'],
  'White blood cell decreased': ['3','4'],
  'Investigations - Other, specify': ['3','4','5'],

  'Acidosis': ['3','4','5'],
  'Alcohol intolerance': ['3',' 4','5'],
  'Alkalosis': ['3','4','5'],
  'Anorexia': ['3','4','5'],
  'Dehydration': ['3','4','5'],
  'Glucose intolerance': ['3','4','5'],
  'Hypercalcemia': ['3','4','5'],
  'Hyperglycemia': ['3','4','5'],
  'Hyperkalemia': ['3','4','5'],
  'Hypermagnesemia': ['3','4','5'],
  'Hypernatremia': ['3','4','5'],
  'Hypertriglyceridemia': ['3','4','5'],
  'Hyperuricemia': ['3','4','5'],
  'Hypoalbuminemia': ['3','4','5'],
  'Hypocalcemia': ['3','4','5'],
  'Hypoglycemia': ['3','4','5'],
  'Hypokalemia': ['3','4','5'],
  'Hypomagnesemia': ['3','4','5'],
  'Hyponatremia': ['3','4','5'],
  'Hypophosphatemia': ['3','4','5'],
  'Iron overload': ['3','4','5'],
  'Obesity': ['3','4'],
  'Tumor lysis syndrome': ['3','4','5'],
  'Metabolism and nutrition disorders - Other, specify': ['3','4','5'],

  'Abdominal soft tissue necrosis': ['3','4','5'],
  'Arthralgia': ['3'],
  'Arthritis': ['3'],
  'Avascular necrosis': ['3','4','5'],
  'Back pain': ['3'],
  'Bone pain': ['3'],
  'Buttock pain': ['3'],
  'Chest wall pain': ['3'],
  'Exostosis': ['3'],
  'Fibrosis deep connective tissue': ['3','4','5'],
  'Flank pain': ['3'],
  'Generalized muscle weakness': ['3'],
  'Growth suppression': ['3'],
  'Head soft tissue necrosis': ['3','4','5'],
  'Joint effusion': ['3'],
  'Joint range of motion decreased': ['3'],
  'Joint range of motion decreased cervical spine': ['3'],
  'Joint range of motion decreased lumbar spine': ['3'],
  'Kyphosis': ['3'],
  'Lordosis': ['3'],
  'Muscle weakness left-sided': ['3'],
  'Muscle weakness lower limb': ['3'],
  'Muscle weakness right-sided': ['3'],
  'Muscle weakness trunk': ['3'],
  'Muscle weakness upper limb': ['3'],
  'Musculoskeletal deformity': ['3'],
  'Myalgia': ['3'],
  'Myositis': ['3'],
  'Neck pain': ['3'],
  'Neck soft tissue necrosis': ['3','4','5'],
  'Osteonecrosis of jaw': ['3','4','5'],
  'Osteoporosis': ['3'],
  'Pain in extremity': ['3'],
  'Pelvic soft tissue necrosis': ['3','4','5'],
  'Scoliosis': ['3'],
  'Soft tissue necrosis lower limb': ['3','4','5'],
  'Soft tissue necrosis upper limb': ['3','4','5'],
  'Superficial soft tissue fibrosis': ['3','4','5'],
  'Trismus': ['3'],
  'Unequal limb length': ['3'],
  'Musculoskeletal and connective tissue disorder - Other, specify': ['3','4','5'],

  'Leukemia secondary to oncology chemotherapy': ['4','5'],
  'Myelodysplastic syndrome': ['4','5'],
  'Treatment related secondary malignancy': ['3','4','5'],
  'Tumor pain': ['3'],
  'Neoplasms benign, malignant, or unspecified (including cysts and polyps) - Other, specify': ['3','4','5'],

  'Abducens nerve disorder': ['3'],
  'Accessory nerve disorder': ['3'],
  'Acoustic nerve disorder NOS': ['3'],
  'Akathisia': ['3'],
  'Amnesia': ['3'],
  'Aphonia': ['3'],
  'Arachnoiditis': ['3','4','5'],
  'Ataxia': ['3'],
  'Brachial plexopathy': ['3'],
  'Central nervous system necrosis': ['3','4','5'],
  'Cerebrospinal fluid leakage': ['3','4','5'],
  'Cognitive disturbance': ['3'],
  'Concentration impairment': ['3'],
  'Depressed level of consciousness': ['3','4','5'],
  'Dizziness': ['3'],
  'Dysarthria': ['3'],
  'Dysesthesia': ['3'],
  'Dysphasia': ['3'],
  'Edema cerebral': ['4'],
  'Encephalopathy': ['3','4','5'],
  'Extrapyramidal disorder': ['3','4','5'],
  'Facial muscle weakness': ['3'],
  'Facial nerve disorder': ['3'],
  'Glossopharyngeal nerve disorder': ['3','4','5'],
  'Headache': ['3'],
  'Hydrocephalus': ['3','4','5'],
  'Hypersomnia': ['3'],
  'Hypoglossal nerve disorder': ['3'],
  'Intracranial hemorrhage': ['3','4','5'],
  'IVth nerve disorder': ['3'],
  'Leukoencephalopathy': ['3','4','5'],
  'Memory impairment': ['3'],
  'Meningismus': ['3','4','5'],
  'Movements involuntary': ['3'],
  'Myelitis': ['3','4','5'],
  'Neuralgia': ['3'],
  'Nystagmus': ['3'],
  'Oculomotor nerve disorder': ['3'],
  'Olfactory nerve disorder': ['3'],
  'Paresthesia': ['3'],
  'Peripheral motor neuropathy': ['3','4','5'],
  'Peripheral sensory neuropathy': ['3','4','5'],
  'Phantom pain': ['3'],
  'Pyramidal tract syndrome': ['3','4','5'],
  'Radiculitis': ['3','4','5'],
  'Recurrent laryngeal nerve palsy': ['3','4','5'],
  'Reversible posterior leukoencephalopathy syndrome': ['3','4','5'],
  'Seizure': ['3','4','5'],
  'Sinus pain': ['3'],
  'Somnolence': ['3','4','5'],
  'Spasticity': ['3','4','5'],
  'Stroke': ['3','4','5'],
  'Syncope': ['3'],
  'Tremor': ['3'],
  'Trigeminal nerve disorder': ['3'],
  'Vagus nerve disorder': ['3','4','5'],
  'Vasovagal reaction': ['3','4','5'],
  'Nervous system disorders - Other, specify': ['3','4','5'],

  'Fetal death': ['5'],
  'Fetal growth retardation': ['3','4'],
  'Premature delivery': ['3','4'],
  'Unintended pregnancy': ['3'],
  'Pregnancy, puerperium, or perinatal conditions - Other, specify': ['3','4','5'],

  'Agitation': ['3','4','5'],
  'Anxiety': ['3','4','5'],
  'Confusion': ['3','4','5'],
  'Delayed orgasm': ['3'],
  'Delirium': ['3','4','5'],
  'Delusions': ['3','4','5'],
  'Depression': ['3','4','5'],
  'Euphoria': ['3'],
  'Hallucinations': ['3','4','5'],
  'Insomnia': ['3'],
  'Libido increased': ['3'],
  'Mania': ['3','4','5'],
  'Personality change': ['3','4','5'],
  'Psychosis': ['3','4','5'],
  'Restlessness': ['3'],
  'Suicidal ideation': ['3','4'],
  'Suicide attempt': ['3','4','5'],
  'Psychiatric disorders - Other, specify': ['3','4','5'],

  'Acute kidney injury': ['3','4','5'],
  'Bladder perforation': ['3','4','5'],
  'Bladder spasm': ['3'],
  'Chronic kidney disease': ['3','4','5'],
  'Cystitis noninfective': ['3','4','5'],
  'Hematuria': ['3','4','5'],
  'Proteinuria': ['3'],
  'Renal calculi': ['3','4','5'],
  'Renal colic': ['3'],
  'Renal hemorrhage': ['3','4','5'],
  'Urinary fistula': ['3','4','5'],
  'Urinary incontinence': ['3'],
  'Urinary retention': ['3','4','5'],
  'Urinary tract obstruction': ['3','4','5'],
  'Urinary tract pain': ['3'],
  'Renal and urinary disorders - Other, specify': ['3','4','5'],

  'Azoospermia': ['3'],
  'Breast atrophy': ['3'],
  'Breast pain': ['3'],
  'Dysmenorrhea': ['3'],
  'Dyspareunia': ['3'],
  'Erectile dysfunction': ['3'],
  'Fallopian tube obstruction': ['3'],
  'Fallopian tube stenosis': ['3','4','5'],
  'Female genital tract fistula': ['3','4','5'],
  'Genital edema': ['3'],
  'Gynecomastia': ['3'],
  'Hematosalpinx': ['3','4','5'],
  'Irregular menstruation': ['3'],
  'Menorrhagia': ['3','4','5'],
  'Oligospermia': ['3'],
  'Ovarian hemorrhage': ['3','4','5'],
  'Ovarian rupture': ['3','4','5'],
  'Ovulation pain': ['3'],
  'Pelvic floor muscle weakness': ['3','4','5'],
  'Pelvic pain': ['3'],
  'Penile pain': ['3'],
  'Perineal pain': ['3'],
  'Premature menopause': ['3'],
  'Prostatic hemorrhage': ['3','4','5'],
  'Prostatic obstruction': ['3'],
  'Prostatic pain': ['3'],
  'Scrotal pain': ['3'],
  'Spermatic cord hemorrhage': ['3','4','5'],
  'Spermatic cord obstruction': ['3'],
  'Testicular disorder': ['3','4','5'],
  'Testicular hemorrhage': ['3','4','5'],
  'Testicular pain': ['3'],
  'Uterine fistula': ['3','4','5'],
  'Uterine hemorrhage': ['3','4','5'],
  'Uterine obstruction': ['3'],
  'Uterine pain': ['3'],
  'Vaginal dryness': ['3'],
  'Vaginal fistula': ['3','4','5'],
  'Vaginal hemorrhage': ['3','4','5'],
  'Vaginal inflammation': ['3','4','5'],
  'Vaginal obstruction': ['3'],
  'Vaginal pain': ['3'],
  'Vaginal perforation': ['3','4','5'],
  'Vaginal stricture': ['3','5'],
  'Vaginismus': ['3'],
  'Reproductive system and breast disorders - Other, specify': ['3','4','5'],

  'Adult respiratory distress syndrome': ['3','4','5'],
  'Apnea': ['3','4','5'],
  'Aspiration': ['3','4','5'],
  'Atelectasis': ['3','4','5'],
  'Bronchial fistula': ['3','4','5'],
  'Bronchial obstruction': ['3','4','5'],
  'Bronchial stricture': ['3','4','5'],
  'Bronchopleural fistula': ['3','4','5'],
  'Bronchopulmonary hemorrhage': ['3','4','5'],
  'Bronchospasm': ['3','4','5'],
  'Chylothorax': ['3','4','5'],
  'Cough': ['3'],
  'Dyspnea': ['3','4','5'],
  'Epistaxis': ['3','4','5'],
  'Hiccups': ['3'],
  'Hoarseness': ['3'],
  'Hypoxia': ['3','4','5'],
  'Laryngeal edema': ['3','4','5'],
  'Laryngeal fistula': ['3','4','5'],
  'Laryngeal hemorrhage': ['3','4','5'],
  'Laryngeal inflammation': ['3'],
  'Laryngeal mucositis': ['3','4','5'],
  'Laryngeal obstruction': ['3','4','5'],
  'Laryngeal stenosis': ['3','4','5'],
  'Laryngopharyngeal dysesthesia': ['3','4','5'],
  'Laryngospasm': ['3','4','5'],
  'Mediastinal hemorrhage': ['3','4','5'],
  'Nasal congestion': ['3'],
  'Pharyngeal fistula': ['3','4','5'],
  'Pharyngeal hemorrhage': ['3','4','5'],
  'Pharyngeal mucositis': ['3','4','5'],
  'Pharyngeal necrosis': ['3','4','5'],
  'Pharyngeal stenosis': ['3','4','5'],
  'Pharyngolaryngeal pain': ['3'],
  'Pleural effusion': ['3','4','5'],
  'Pleural hemorrhage': ['3','4','5'],
  'Pleuritic pain': ['3'],
  'Pneumonitis': ['3','4','5'],
  'Pneumothorax': ['3','4','5'],
  'Productive cough': ['3'],
  'Pulmonary edema': ['3','4','5'],
  'Pulmonary fibrosis': ['3','4','5'],
  'Pulmonary fistula': ['3','4','5'],
  'Pulmonary hypertension': ['3','4','5'],
  'Respiratory failure': ['4','5'],
  'Retinoic acid syndrome': ['3','4','5'],
  'Sinus disorder': ['3','4','5'],
  'Sleep apnea': ['3','4','5'],
  'Sore throat': ['3'],
  'Stridor': ['3','4','5'],
  'Tracheal fistula': ['3','4','5'],
  'Tracheal mucositis': ['3','4','5'],
  'Tracheal stenosis': ['3','4','5'],
  'Voice alteration': ['3'],
  'Wheezing': ['3','4','5'],
  'Respiratory, thoracic and mediastinal disorders - Other, specify': ['3','4','5'],

  'Bullous dermatitis': ['3','4','5'],
  'Dry skin': ['3'],
  'Erythema multiforme': ['3','4','5'],
  'Erythroderma': ['3','4','5'],
  'Fat atrophy': ['3'],
  'Hyperhidrosis': ['3'],
  'Hypohidrosis': ['3','4','5'],
  'Lipohypertrophy': ['3'],
  'Pain of skin': ['3'],
  'Palmar-plantar erythrodysesthesia syndrome': ['3'],
  'Periorbital edema': ['3'],
  'Photosensitivity': ['3','4','5'],
  'Pruritus': ['3'],
  'Purpura': ['3'],
  'Rash acneiform': ['3','4','5'],
  'Rash maculo-papular': ['3'],
  'Scalp pain': ['3'],
  'Skin atrophy': ['3'],
  'Skin induration': ['3','4','5'],
  'Skin ulceration': ['3','4','5'],
  'Stevens-Johnson syndrome': ['3','4','5'],
  'Toxic epidermal necrolysis': ['4','5'],
  'Urticaria': ['3'],
  'Skin and subcutaneous tissue disorders - Other, specify': ['3','4','5'],

  'Menopause': ['3'],
  'Social circumstances - Other, specify': ['3','4','5'],

  'Surgical and medical procedures - Other, specify': ['3','4','5'],

  'Capillary leak syndrome': ['3','4','5'],
  'Flushing': ['3'],
  'Hematoma': ['3','4','5'],
  'Hot flashes': ['3'],
  'Hypertension': ['3','4','5'],
  'Hypotension': ['3','4','5'],
  'Lymph leakage': ['3','4','5'],
  'Lymphedema': ['3'],
  'Lymphocele': ['3'],
  'Peripheral ischemia': ['3','4','5'],
  'Superior vena cava syndrome': ['3','4','5'],
  'Thromboembolic event': ['3','4','5'],
  'Vasculitis': ['3','4','5'],
  'Visceral arterial ischemia': ['3','4','5'],
  'Vascular disorders - Other, specify': ['3','4','5']
})
.value('categoryTypes', 
  [
    {'category': 'Blood and lymphatic system disorders', 'type': 'blood'},
    {'category': 'Cardiac disorders', 'type': 'cardiac'},
    {'category': 'Congenital, familial and genetic disorders', 'type': 'congenital' },
    {'category': 'Ear and labyrinth disorders', 'type': 'ear'},
    {'category': 'Endocrine disorders', 'type': 'endocrine'},
    {'category': 'Eye disorders', 'type': 'eye'},
    {'category': 'Gastrointestinal disorders', 'type': 'gastro'},
    {'category': 'General disorders and administration site conditions', 'type': 'general'},
    {'category': 'Hepatobiliary disorders', 'type': 'hepatobiliary'},
    {'category': 'Immune system disorders', 'type': 'immune'},
    {'category': 'Infections and infestations', 'type': 'infection'},
    {'category': 'Injury, poisoning and procedural complications', 'type': 'complications'},
    {'category': 'Investigations', 'type': 'investigations'},
    {'category': 'Metabolism and nutrition disorders', 'type': 'metabolism'},
    {'category': 'Musculoskeletal and connective tissue disorders', 'type': 'musculoskeletal'},
    {'category': 'Neoplasms benign, malignant, or unspecified (including cysts and polyps)', 'type': 'neoplasms'},
    {'category': 'Nervous system disorders', 'type': 'nervous_system'},
    {'category': 'Pregnancy, puerperium and perinatal conditions', 'type': 'pregnancy'},
    {'category': 'Psychiatric disorders', 'type': 'psych'},
    {'category': 'Renal and urinary disorders', 'type': 'renal'},
    {'category': 'Reproductive system and breast disorders', 'type': 'reproductive'},
    {'category': 'Respiratory, thoracic and mediastinal disorders', 'type': 'respiratory'},
    {'category': 'Skin and subcutaneous tissue disorders', 'type': 'skin'},
    {'category': 'Social circumstances', 'type': 'social'},
    {'category': 'Surgical and medical procedures', 'type': 'surgical'},
    {'category': 'Vascular disorders', 'type': 'vascular'}
  ]
);
